# ===========================================================

FROM node:latest as builder

WORKDIR /apps
COPY . .

RUN yarn install && yarn build:www

# ===========================================================
FROM nginx:1.19

WORKDIR /usr/share/nginx/html

COPY env.sh .

RUN apk add --no-cache bash; chmod +x env.sh

COPY --from=builder /apps/packages/apps/build /usr/share/nginx/html

EXPOSE 80

CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh"]

CMD ["nginx", "-g", "daemon off;"]
